/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ff9c2491-dca6-453e-9c4e-0c4348258316",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_i7Fu6R9uG",
    "aws_user_pools_web_client_id": "13b7v66c8h95ic3vo7v2k3flbe",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nui67tiayrbalbx3unt7bb7smi.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
